#Rename this to extra_model_paths.yaml and ComfyUI will load it


#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
# a111:
#     base_path: path/to/stable-diffusion-webui/

#     checkpoints: models/Stable-diffusion
#     configs: models/Stable-diffusion
#     vae: models/VAE
#     loras: |
#          models/Lora
#          models/LyCORIS
#     upscale_models: |
#                   models/ESRGAN
#                   models/RealESRGAN
#                   models/SwinIR
#     embeddings: embeddings
#     hypernetworks: models/hypernetworks
#     controlnet: models/ControlNet

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

comfyui:
    base_path: /mnt/models/
    # You can use is_default to mark that these folders should be listed first, and used as the default dirs for eg downloads
    is_default: true
    checkpoints: comfy_models/checkpoints/
    clip: comfy_models/clip/
    clip_vision: comfy_models/clip_vision/
    configs: comfy_models/configs/
    controlnet: comfy_models/controlnet/
    diffusion_models: |
                 comfy_models/diffusion_models
                 comfy_models/unet
    embeddings: comfy_models/embeddings/
    loras: comfy_models/loras/
    upscale_models: comfy_models/upscale_models/
    vae: comfy_models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
